---
argument_specs:
  main:
    short_description: Zabbix Repo
    description:
      - This role installs the Zabbix official repository on a Linux system.
    author:
      - Jim Tarpley (@trippsc2)
    options:
      zbx_major_version:
        type: str
        required: true
        choices:
          - '7.2'
          - '7.0'
        description:
          - The major version of Zabbix to be deployed.
