---
galaxy_info:
  author: Jim Tarpley (@trippsc2)
  namespace: trippsc2
  role_name: repo
  description: This role installs the Zabbix official repository on a Linux system.
  license: MIT

  min_ansible_version: '2.16'

  platforms:
    - name: Debian
      versions:
        - bookworm
    - name: EL
      versions:
        - '9'
        - '8'
    - name: Ubuntu
      versions:
        - noble
        - jammy

dependencies: []
