---
galaxy_info:
  author: Jim Tarpley (@trippsc2)
  namespace: trippsc2
  role_name: proxy_sqlite3
  description: This role installs a SQLite3 database for use by a Zabbix Proxy on a Linux system.
  
  license: MIT

  min_ansible_version: '2.16'

  platforms:
    - name: Debian
      versions:
        - bookworm
    - name: EL
      versions:
        - '9'
        - '8'
    - name: Ubuntu
      versions:
        - noble
        - jammy

dependencies:
  - role: trippsc2.zabbix.repo
