---
galaxy_info:
    author: Jim Tarpley (@trippsc2)
    namespace: trippsc2
    role_name: agent2
    description: This role installs the Zabbix Agent 2 on a Linux or Windows system.
    license: MIT

    min_ansible_version: '2.16'

    platforms:
      - name: Debian
        versions:
          - bullseye
          - bookworm
      - name: EL
        versions:
          - '8'
          - '9'
      - name: Fedora
        versions:
          - all
      - name: Ubuntu
        versions:
          - focal
          - jammy
          - noble
      - name: Windows
        versions:
          - '2019'
          - '2022'

collections:
  - ansible.posix
  - ansible.windows
  - chocolatey.chocolatey
  - community.general
  - community.vmware
  - community.zabbix

dependencies: []
