---
- name: Ensure PHP is configured for Zabbix server
  become: true
  ansible.builtin.template:
    src: zabbix.php-fpm.conf.j2
    dest: "{{ _zbxserver_php_fpm_config_file_path }}"
    owner: "{{ nginx_user }}"
    group: "{{ nginx_group }}"
    mode: '0644'
  notify:
    - _zbxserver_restart_php-fpm

- name: Ensure Zabbix web configuration directory exists and has proper permissions
  become: true
  ansible.builtin.file:
    path: /etc/zabbix/web
    state: directory
    owner: "{{ nginx_user }}"
    group: "{{ nginx_group }}"
    mode: '0755'

- name: Ensure Zabbix web configuration is desired
  become: true
  ansible.builtin.template:
    src: zabbix.conf.php.j2
    dest: /etc/zabbix/web/zabbix.conf.php
    owner: "{{ nginx_user }}"
    group: "{{ nginx_group }}"
    mode: '0664'
  notify:
    - _zbxserver_restart_php-fpm

- name: Ensure PHP-FPM service is enabled
  become: true
  ansible.builtin.systemd_service:
    name: "{{ _zbxserver_php_fpm_service_name }}"
    enabled: true

- name: Ensure NGINX is installed and configured
  ansible.builtin.include_role:
    name: trippsc2.nginx.oss

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Ensure PHP-FPM service is started
  become: true
  ansible.builtin.systemd_service:
    name: "{{ _zbxserver_php_fpm_service_name }}"
    state: started
