---
- name: Gather OS facts
  when:
    - ansible_distribution is not defined or
      ansible_distribution_major_version is not defined or
      ansible_distribution_release is not defined or
      ansible_os_family is not defined
  ansible.builtin.setup:
    gather_subset:
      - '!all'
      - '!min'
      - distribution
      - distribution_major_version
      - distribution_release
      - os_family

- name: Validate
  ansible.builtin.import_tasks: validate.yml

- name: Include OS family variables
  ansible.builtin.include_vars: "{{ ansible_os_family }}/main.yml"

- name: Include non-EL release variables
  when:
    - ansible_os_family != 'RedHat'
  ansible.builtin.include_vars: "{{ ansible_distribution }}/{{ ansible_distribution_release }}.yml"

- name: Install packages
  ansible.builtin.include_tasks: "install/{{ ansible_os_family }}.yml"

- name: Configure SELinux
  when:
    - zbxserver_configure_selinux
  ansible.builtin.include_tasks: selinux.yml

- name: Configure Zabbix
  ansible.builtin.import_tasks: configure.yml
