---
- name: Validate
  ansible.builtin.import_tasks: validate.yml

- name: Install packages
  ansible.builtin.include_tasks: "install/{{ ansible_os_family }}.yml"

- name: Configure SELinux
  when:
    - _zbxserver_configure_selinux
  ansible.builtin.include_tasks: selinux.yml

- name: Configure Zabbix
  ansible.builtin.import_tasks: configure.yml
