---
- name: Validate EL major version
  when:
    - ansible_os_family == 'RedHat'
  ansible.builtin.assert:
    that:
      - zbxserver_major_version in _zbxserver_el_supported_major_versions[ansible_distribution_major_version]
    fail_msg: "{{ ansible_distribution }} {{ ansible_distribution_major_version }} is not supported running Zabbix {{ zbxserver_major_version }}. Supported versions for this distribution are: '{{ _zbxserver_el_supported_major_versions[ansible_distribution_major_version] | join(''', ''') }}'."
    success_msg: "{{ ansible_distribution }} {{ ansible_distribution_major_version }} is supported running Zabbix {{ zbxserver_major_version }}."

- name: Validate non-EL major version
  when:
    - ansible_os_family != 'RedHat'
  ansible.builtin.assert:
    that:
      - zbxserver_major_version in _zbxserver_non_el_supported_major_versions[ansible_distribution_release]
    fail_msg: "{{ ansible_distribution }} {{ ansible_distribution_release }} is not supported running Zabbix {{ zbxserver_major_version }}. Supported versions for this distribution are: '{{ _zbxserver_non_el_supported_major_versions[ansible_distribution_release] | join(''', ''') }}'."
    success_msg: "{{ ansible_distribution }} {{ ansible_distribution_release }} is supported running Zabbix {{ zbxserver_major_version }}."

- name: Validate NGINX module version (EL-only)
  when:
    - ansible_os_family == 'RedHat'
  ansible.builtin.assert:
    that:
      - zbxserver_nginx_module_version in _zbxserver_nginx_module_versions_allowed
    fail_msg: "Unsupported NGINX module version '{{ zbxserver_nginx_module_version }}' for Zabbix major version '{{ zbxserver_major_version }}'. Supported versions are '{{ _zbxserver_nginx_module_versions_allowed | join(''', ''') }}'."
    success_msg: "NGINX module version '{{ zbxserver_nginx_module_version }}' for Zabbix major version '{{ zbxserver_major_version }}' is supported."

- name: Validate PHP module version (EL-only)
  when:
    - ansible_os_family == 'RedHat'
  ansible.builtin.assert:
    that:
      - zbxserver_php_module_version in _zbxserver_php_module_versions_allowed
    fail_msg: "Unsupported PHP module version '{{ zbxserver_php_module_version }}' for Zabbix major version '{{ zbxserver_major_version }}'. Supported versions are '{{ _zbxserver_php_module_versions_allowed | join(''', ''') }}'."
    success_msg: "PHP module version '{{ zbxserver_php_module_version }}' for Zabbix major version '{{ zbxserver_major_version }}' is supported."

- name: Validate Vault URL
  when:
    - zbxserver_configure_vault
  ansible.builtin.assert:
    that:
      - zbxserver_vault_url is defined
    fail_msg: Vault URL is not defined.
    success_msg: Vault URL is defined.

- name: Validate Vault token
  when:
    - zbxserver_configure_vault
  ansible.builtin.assert:
    that:
      - zbxserver_vault_token is defined
    fail_msg: Vault token is not defined.
    success_msg: Vault token is defined.

- name: Validate database CA certificate file
  when:
    - zbxserver_database_use_ssl
  ansible.builtin.assert:
    that:
      - zbxserver_database_ca_file is defined
    fail_msg: Database CA certificate file is not defined.
    success_msg: Database CA certificate file is defined.
