---
- name: Ensure Zabbix server packages are installed
  become: true
  ansible.builtin.apt:
    name:
      - "{{ _zbxserver_package_name }}"
    state: present
    update_cache: true

- name: Ensure SELinux management packages are installed
  when:
    - _zbxserver_configure_selinux
  become: true
  ansible.builtin.apt:
    name: "{{ _zbxserver_selinux_packages }}"
    state: present
