---
- name: Create Zabbix host groups
  delegate_to: localhost
  throttle: 1
  community.zabbix.zabbix_group:
    host_groups: "{{ zbxhost_groups }}"
    state: present

- name: Create Zabbix host
  delegate_to: localhost
  community.zabbix.zabbix_host:
    host_name: "{{ zbxhost_name }}"
    visible_name: "{{ zbxhost_visible_name | default(omit) }}"
    host_groups: "{{ zbxhost_groups }}"
    interfaces: "{{ zbxhost_interfaces }}"
    link_templates: "{{ zbxhost_templates }}"
    status: enabled
    tls_accept: "{{ _zbxhost_tls_accept }}"
    tls_connect: "{{ _zbxhost_tls_connect }}"
    proxy: "{{ zbxhost_proxy | default(omit) }}"
    state: present

- name: Create Zabbix host macros
  loop: "{{ zbxhost_macros }}"
  delegate_to: localhost
  community.zabbix.zabbix_hostmacro:
    host_name: "{{ zbxhost_name }}"
    macro_name: "{{ item.name }}"
    macro_type: "{{ item.type | default('text') }}"
    macro_value: "{{ item.value }}"
    state: present
