---
- name: Install Zabbix Agent 2
  become: true
  ansible.builtin.dnf:
    name:
      - zabbix-agent2
    state: present

- name: Install MongoDB plugin
  when:
    - zbxagent_install_mongodb_plugin
  become: true
  ansible.builtin.dnf:
    name:
      - zabbix-agent2-plugin-mongodb
    state: present

- name: Install PostgreSQL plugin
  when:
    - zbxagent_install_pgsql_plugin
  become: true
  ansible.builtin.dnf:
    name:
      - zabbix-agent2-plugin-postgresql
    state: present
