---
- name: Prepare PostgreSQL
  hosts:
    - subjects
  pre_tasks:
    - name: Bootstrap python for Ansible
      become: true
      ansible.builtin.raw: |
        command -v python3 python || (
        command -v apk >/dev/null && sudo apk add --no-progress --update python3 ||
        (test -e /usr/bin/dnf && sudo dnf install -y python3) ||
        (test -e /usr/bin/apt && (apt -y update && apt install -y python-minimal)) ||
        (test -e /usr/bin/yum && sudo yum -y -qq install python3) ||
        (test -e /usr/sbin/pkg && sudo env ASSUME_ALWAYS_YES=yes pkg update && sudo env ASSUME_ALWAYS_YES=yes pkg install python3) ||
        (test -e /usr/sbin/pkg_add && sudo /usr/sbin/pkg_add -U -I -x python%3.7) ||
        echo "Warning: Python not bootstrapped due to unknown platform."
        )
      changed_when: false

    - name: Set OS variables (Debian-based)
      when:
        - ansible_os_family == 'Debian'
      ansible.builtin.set_fact:
        _pgsql_home_directory: /var/lib/postgresql

    - name: Set OS variables (Red Hat-based)
      when:
        - ansible_os_family == 'RedHat'
      ansible.builtin.set_fact:
        _pgsql_home_directory: /var/lib/pgsql

    - name: Create postgres group
      become: true
      ansible.builtin.group:
        name: postgres
        state: present
        system: true

    - name: Create postgres user
      become: true
      ansible.builtin.user:
        name: postgres
        group: postgres
        system: true
        shell: /usr/sbin/nologin
        password: '!'
        password_lock: true
        home: "{{ _pgsql_home_directory }}"
        createhome: false
        comment: PostgreSQL Server
        state: present
  roles:
    - role: trippsc2.hashi_vault.testing_ca
    - role: trippsc2.hashi_vault.signed_certificate
      vars:
        cert_certificate_path: "{{ pgsql_ssl_cert_file }}"
        cert_private_key_path: "{{ pgsql_ssl_key_file }}"
        cert_certificate_owner: postgres
        cert_certificate_group: postgres
        cert_private_key_owner: postgres
        cert_private_key_group: postgres
        cert_common_name: "{{ inventory_hostname }}"
        cert_subject_alternative_names:
          - "DNS:{{ inventory_hostname }}"
          - DNS:localhost
          - "IP:{{ ansible_host }}"
          - IP:127.0.0.1
        cert_copy_ca_chain: true
        cert_ca_chain_path: "{{ pgsql_ssl_ca_file }}"
    - role: trippsc2.zabbix.server_postgresql

- name: Prepare Zabbix
  hosts:
    - subjects
  roles:
    - role: trippsc2.hashi_vault.signed_certificate
      vars:
        cert_certificate_path: "{{ zbxserver_db_tls_cert_file }}"
        cert_private_key_path: "{{ zbxserver_db_tls_key_file }}"
        cert_certificate_owner: zabbix
        cert_certificate_group: zabbix
        cert_private_key_owner: zabbix
        cert_private_key_group: zabbix
        cert_common_name: "{{ inventory_hostname }}"
        cert_subject_alternative_names:
          - "DNS:{{ inventory_hostname }}"
          - DNS:localhost
          - "IP:{{ ansible_host }}"
          - IP:127.0.0.1
    - role: trippsc2.zabbix.server

- name: Prepare NGINX
  hosts:
    - subjects
  pre_tasks:
    - name: Set OS variables (Debian-based)
      when:
        - ansible_os_family == 'Debian'
      ansible.builtin.set_fact:
        _nginx_home_directory: /var/www
        _nginx_user: www-data
        _nginx_group: www-data

    - name: Set OS variables (Red Hat-based)
      when:
        - ansible_os_family == 'RedHat'
      ansible.builtin.set_fact:
        _pgsql_home_directory: /var/lib/nginx
        _nginx_user: nginx
        _nginx_group: nginx

    - name: Create nginx group
      become: true
      ansible.builtin.group:
        name: "{{ _nginx_group }}"
        state: present
        system: true
    
    - name: Create nginx user
      become: true
      ansible.builtin.user:
        name: "{{ _nginx_user }}"
        group: "{{ _nginx_group }}"
        system: true
        shell: /usr/sbin/nologin
        password: '!'
        password_lock: true
        home: "{{ _nginx_home_directory }}"
        createhome: false
        comment: Nginx web server
        state: present
  roles:
    - role: trippsc2.hashi_vault.signed_certificate
      vars:
        cert_certificate_path: "{{ zbxserver_web_cert_file }}"
        cert_private_key_path: "{{ zbxserver_web_key_file }}"
        cert_certificate_owner: "{{ _nginx_user }}"
        cert_certificate_group: "{{ _nginx_group }}"
        cert_private_key_owner: "{{ _nginx_user }}"
        cert_private_key_group: "{{ _nginx_group }}"
        cert_common_name: "{{ inventory_hostname }}"
        cert_subject_alternative_names:
          - "DNS:{{ inventory_hostname }}"
          - DNS:localhost
          - "IP:{{ ansible_host }}"
          - IP:127.0.0.1
