---
- name: Configure ODBC ini file
  loop:
    - option: Driver
      value: "{{ _zbxserver_mssql_odbc_connection.driver | default('ODBC Driver 18 for SQL Server') }}"
    - option: Server
      value: "{{ _zbxserver_mssql_odbc_connection.uri }}"
    - option: Encrypt
      value: "{{ _zbxserver_mssql_odbc_connection.encrypt | default(true) | ternary('yes', 'no') }}"
  become: true
  community.general.ini_file:
    path: /etc/odbc.ini
    section: "{{ _zbxserver_mssql_odbc_connection.name }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
    state: present
    owner: root
    group: root
    mode: '0644'
