---
- name: Install Microsoft GPG key
  become: true
  ansible.builtin.get_url:
    url: https://packages.microsoft.com/keys/microsoft.asc
    dest: /etc/apt/trusted.gpg.d/microsoft.asc
    owner: root
    group: root
    mode: '0644'

- name: Install Microsoft repository
  become: true
  ansible.builtin.apt_repository:
    repo: "{{ _zbxserver_microsoft_apt_repo_config }}"
    filename: mssql-release
    state: present

- name: Install Microsoft ODBC packages
  become: true
  environment:
    ACCEPT_EULA: Y
  ansible.builtin.apt:
    name:
      - msodbcsql18
      - mssql-tools18
    state: present
    update_cache: true
