---
namespace: trippsc2
name: zabbix
version: 1.0.0
readme: README.md
authors:
  - Jim Tarpley
description: This collection contains roles for installing and configuring Zabbix.

license_file: 'LICENSE'

tags: []

dependencies:
  ansible.posix: ">=1.0.0"
  community.general: ">=1.0.0"
  community.hashi_vault: ">=4.2.0"
  community.postgresql: ">=1.0.0"
  community.zabbix: ">=2.1.0"
  trippsc2.hashi_vault: ">=1.3.6"
  trippsc2.nginx: ">=1.0.7"
  trippsc2.postgresql: ">=1.0.4"

repository: https://github.com/trippsc2/ansible-collection-zabbix.git

build_ignore:
  - .gitignore
