---
namespace: trippsc2
name: zabbix
version: 1.1.12
readme: README.md
authors:
  - Jim Tarpley (@trippsc2)
description: This collection contains roles for installing and configuring Zabbix.

license_file: 'LICENSE'

tags:
  - infrastructure
  - linux
  - monitoring

dependencies:
  ansible.posix: ">=1.0.0"
  ansible.utils: ">=2.2.0"
  community.general: ">=8.1.0"
  community.hashi_vault: ">=4.2.0"
  community.postgresql: ">=1.0.0"
  community.vmware: ">=1.0.0"
  community.zabbix: ">=3.3.0"
  trippsc2.hashi_vault: ">=1.3.6"
  trippsc2.nginx: ">=1.0.7"
  trippsc2.postgresql: ">=1.0.4"

repository: https://github.com/trippsc2/ansible-collection-zabbix.git

manifest:
  directives:
    - recursive-include roles/* *.md
    - recursive-include roles/*/files **
    - exclude galaxy.yml galaxy.yaml MANIFEST.json FILES.json *.tar.gz
    - recursive-exclude tests/output **
    - recursive-exclude roles/*/molecule **
    - recursive-exclude molecule **
    - global-exclude /.* /__pycache__
