---
- name: Gather OS facts
  when:
    - ansible_os_family is not defined
  ansible.builtin.setup:
    gather_subset:
      - '!all'
      - '!min'
      - os_family

- name: Install Zabbix repository
  when:
    - ansible_os_family != 'Windows'
  ansible.builtin.include_role:
    name: trippsc2.zabbix.repo

- name: Install Zabbix Agent 2
  ansible.builtin.include_tasks: "{{ ansible_os_family }}.yml"
