---
- name: Gather OS facts
  when:
    - ansible_distribution is not defined or
      ansible_distribution_major_version is not defined or
      ansible_distribution_release is not defined or
      ansible_os_family is not defined
  ansible.builtin.setup:
    gather_subset:
      - '!all'
      - '!min'
      - distribution
      - distribution_major_version
      - distribution_release
      - os_family

- name: Validate Zabbix major version is defined
  when:
    - ansible_os_family != 'Windows'
  ansible.builtin.assert:
    that:
      - zbxagent_major_version is defined
    fail_msg: "The 'zbxagent_major_version' variable is not defined."
    success_msg: "The 'zbxagent_major_version' variable is defined."

- name: Install Zabbix repository
  when:
    - ansible_os_family != 'Windows'
  ansible.builtin.include_role:
    name: trippsc2.zabbix.repo

- name: Validate
  ansible.builtin.import_tasks: validate.yml

- name: Install Zabbix Agent 2
  ansible.builtin.include_tasks: "{{ ansible_os_family }}.yml"
