---
- name: Install Zabbix repository
  when:
    - ansible_os_family != 'Windows'
  ansible.builtin.include_role:
    name: trippsc2.zabbix.repo

- name: Validate
  ansible.builtin.import_tasks: validate.yml

- name: Install Zabbix Agent 2
  ansible.builtin.include_tasks: "{{ ansible_os_family }}.yml"
