---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: libvirt
  cachier: machine
  parallel: true
platforms:
  - name: linux
    box: jtarpley/${MOLECULE_BOX:-rocky9_cis}
    memory: 2048
    cpus: 2
    provider_options:
      default_prefix: zabbix_proxy_postgresql_
    groups:
      - subjects
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        vault_token: 47542cbc-6bf8-4fba-8eda-02e0a0d29a0a
        vault_url: "http://{{ hostvars['linux'].ansible_host }}:8200"        
      subjects:
        pgsql_major_version: '17'
        pgsql_ssl: true
        pgsql_ssl_ca_file: >-
          {{ '/etc/pki/ca-trust/source/anchors/ca_chain.crt' if ansible_os_family == 'RedHat' else '/usr/local/share/ca-certificates/ca_chain.crt' }}
        pgsql_ssl_cert_file: >-
          {{ '/etc/pki/tls/certs/proxy.crt' if ansible_os_family == 'RedHat' else '/etc/ssl/certs/proxy.crt' }}
        pgsql_ssl_key_file: >-
          {{ '/etc/pki/tls/private/proxy.key' if ansible_os_family == 'RedHat' else '/etc/ssl/private/proxy.key' }}
        pgsql_log_to_csvlog: true
        pgsql_log_to_syslog: true
        pgsql_vault_ssl_mode: verify-full
        pgsql_vault_access_hostname: "{{ ansible_host }}"
        pgsql_vault_ip_addresses: >-
          {{ [ansible_host] if zbxproxy_pgsql_standalone else [] }}
        zbxproxy_ip_addresses:
          - "{{ ansible_host }}"
        zbxproxy_pgsql_standalone: ${MOLECULE_PGSQL_STANDALONE:-false}
        zbxproxy_major_version: '${MOLECULE_ZABBIX_MAJOR_VERSION:-7.2}'
        zbxproxy_vault_database_mount_point: zabbix
        zbxproxy_vault_database_path: database
verifier:
  name: ansible
