---
galaxy_info:
  author: Jim Tarpley (@trippsc2)
  namespace: trippsc2
  role_name: nginx
  description: This role installs NGINX as a web frontend for Zabbix Server on a Linux system.
  license: MIT

  min_ansible_version: '2.16'

  platforms:
    - name: Debian
      versions:
        - bookworm
    - name: EL
      versions:
        - '9'
        - '8'
    - name: Ubuntu
      versions:
        - noble
        - jammy
        - focal

collections:
  - ansible.posix
  - trippsc2.nginx

dependencies:
  - role: trippsc2.zabbix.repo
