---
galaxy_info:
    author: Jim Tarpley
    namespace: trippsc2
    role_name: nginx
    description: This role installs NGINX as a web frontend for Zabbix Server on a Linux machine.
    license: MIT

    min_ansible_version: '2.14'

    platforms:
      - name: Debian
        versions:
          - bullseye
          - bookworm
      - name: EL
        versions:
          - '8'
          - '9'
      - name: Ubuntu
        versions:
          - focal
          - jammy
          - noble

collections: []

dependencies:
  - role: trippsc2.zabbix.repo
