---
- name: Add firewalld service
  when:
    - zbxproxy_listen_port == 10051
  become: true
  ansible.posix.firewalld:
    service: zabbix-server
    state: enabled
    permanent: true
    immediate: true

- name: Add firewalld port
  when:
    - zbxproxy_listen_port != 10051
  become: true
  ansible.posix.firewalld:
    port: "{{ zbxproxy_listen_port }}/tcp"
    state: enabled
    permanent: true
    immediate: true
