---
- name: Add Zabbix proxy to server (Zabbix 6.4)
  when:
    - zbxproxy_major_version == '6.4'
  block:
    - name: Add Zabbix active proxy to server (Zabbix 6.4)
      when:
        - zbxproxy_active
      community.zabbix.zabbix_proxy:
        proxy_address: "{{ zbxproxy_addresses | join(',') }}"
        proxy_group: "{{ zbxproxy_group_name | default(omit) }}"
        proxy_name: "{{ zbxproxy_name }}"
        state: present
        status: passive
        tls_connect: "{{ _zbxproxy_tls_connect }}"
        tls_psk: "{{ zbxproxy_tls_psk | default(omit) }}"
        tls_psk_identity: "{{ zbxproxy_tls_psk_identity | default(omit) }}"
        tls_subject: "{{ zbxproxy_tls_subject | default(omit) }}"

    - name: Add Zabbix passive proxy to server (Zabbix 6.4)
      when:
        - not zbxproxy_active
      community.zabbix.zabbix_proxy:
        interface:
          dns: "{{ omit if _zbxproxy_address_is_ip else zbxproxy_address }}"
          ip: "{{ zbxproxy_address if _zbxproxy_address_is_ip else omit }}"
          port: "{{ zbxproxy_listen_port }}"
          useip: "{{ _zbxproxy_address_is_ip | ternary('1', '0') }}"
        proxy_group: "{{ zbxproxy_group_name | default(omit) }}"
        proxy_name: "{{ zbxproxy_name }}"
        state: present
        status: active
        tls_accept: "{{ _zbxproxy_tls_accept }}"
        tls_psk: "{{ zbxproxy_tls_psk | default(omit) }}"
        tls_psk_identity: "{{ zbxproxy_tls_psk_identity | default(omit) }}"
        tls_subject: "{{ zbxproxy_tls_subject | default(omit) }}"

- name: Add Zabbix proxy to server (Zabbix 7.0+)
  when:
    - zbxproxy_major_version != '6.4'
  block:
    - name: Add Zabbix active proxy to server (Zabbix 7.0+)
      when:
        - zbxproxy_active
      community.zabbix.zabbix_proxy:
        allowed_addresses: "{{ zbxproxy_addresses | join(',') }}"
        operating_mode: active
        proxy_group: "{{ zbxproxy_group_name | default(omit) }}"
        proxy_name: "{{ zbxproxy_name }}"
        state: present
        tls_accept: "{{ _zbxproxy_tls_accept }}"
        tls_psk: "{{ zbxproxy_tls_psk | default(omit) }}"
        tls_psk_identity: "{{ zbxproxy_tls_psk_identity | default(omit) }}"
        tls_subject: "{{ zbxproxy_tls_subject | default(omit) }}"

    - name: Add Zabbix passive proxy to server (Zabbix 7.0+)
      when:
        - not zbxproxy_active
      community.zabbix.zabbix_proxy:
        address: "{{ zbxproxy_address }}"
        operating_mode: passive
        port: "{{ zbxproxy_listen_port }}"
        proxy_group: "{{ zbxproxy_group_name | default(omit) }}"
        proxy_name: "{{ zbxproxy_name }}"
        state: present
        tls_connect: "{{ _zbxproxy_tls_connect }}"
        tls_psk: "{{ zbxproxy_tls_psk | default(omit) }}"
        tls_psk_identity: "{{ zbxproxy_tls_psk_identity | default(omit) }}"
        tls_subject: "{{ zbxproxy_tls_subject | default(omit) }}"
