---
- name: Add Zabbix proxy to server (Zabbix 7.0+)
  block:
    - name: Add Zabbix active proxy to server (Zabbix 7.0+)
      when:
        - zbxproxy_active
      community.zabbix.zabbix_proxy:
        allowed_addresses: "{{ zbxproxy_addresses | join(',') }}"
        operating_mode: active
        proxy_group: "{{ zbxproxy_group_name | default(omit) }}"
        proxy_name: "{{ zbxproxy_name }}"
        state: present
        tls_accept: "{{ _zbxproxy_tls_accept }}"
        tls_psk: "{{ zbxproxy_tls_psk | default(omit) }}"
        tls_psk_identity: "{{ zbxproxy_tls_psk_identity | default(omit) }}"
        tls_subject: "{{ zbxproxy_tls_subject | default(omit) }}"

    - name: Add Zabbix passive proxy to server (Zabbix 7.0+)
      when:
        - not zbxproxy_active
      community.zabbix.zabbix_proxy:
        address: "{{ zbxproxy_address }}"
        operating_mode: passive
        port: "{{ zbxproxy_listen_port }}"
        proxy_group: "{{ zbxproxy_group_name | default(omit) }}"
        proxy_name: "{{ zbxproxy_name }}"
        state: present
        tls_connect: "{{ _zbxproxy_tls_connect }}"
        tls_psk: "{{ zbxproxy_tls_psk | default(omit) }}"
        tls_psk_identity: "{{ zbxproxy_tls_psk_identity | default(omit) }}"
        tls_subject: "{{ zbxproxy_tls_subject | default(omit) }}"
