---
_zbxserver_default_configure_selinux: false

_zbxserver_default_additional_groups:
  - ssl-cert

_zbxserver_selinux_packages:
  - python3-selinux
  - python3-semanage

_zbxserver_default_configure_firewalld: "{{ ansible_distribution == 'Debian' }}"
_zbxserver_default_configure_ufw: "{{ ansible_distribution != 'Debian' }}"

_zbxserver_env_file_path: /etc/default/zabbix-server
_zbxserver_exec_stop_command: >-
  /bin/sh -c '[ -n "$1" ] && kill -s TERM "$1"' -- "$MAINPID"
