---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: libvirt
  cachier: machine
  parallel: true
platforms:
  - name: linux
    box: jtarpley/${MOLECULE_BOX:-rocky9_cis}
    memory: 2048
    cpus: 2
    provider_options:
      default_prefix: zabbix_agent2_linux_
    groups:
      - subjects
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        vault_token: 47542cbc-6bf8-4fba-8eda-02e0a0d29a0a
        vault_url: "http://{{ hostvars['linux'].ansible_host }}:8200"
        _zbxagent_ca_file: >-
          {{ '/etc/pki/ca-trust/source/anchors/vault.crt' if ansible_os_family == 'RedHat' else '/usr/local/share/ca-certificates/vault.crt' }}
      subjects:
        zbxagent_major_version: '${MOLECULE_ZABBIX_MAJOR_VERSION:-7.2}'
        zbxagent_install_ember_plus_plugin: true
        zbxagent_install_mongodb_plugin: true
        zbxagent_install_mssql_plugin: true
        zbxagent_install_pgsql_plugin: true
        zbxagent_servers:
          - "{{ hostvars['linux'].ansible_host }}"
        zbxagent_active_servers:
          - "{{ hostvars['linux'].ansible_host }}"
        zbxagent_tls_connect: cert
        zbxagent_tls_accept: cert
        zbxagent_tls_ca_file: "{{ _zbxagent_ca_file }}"
        zbxagent_tls_cert_file: >-
          {{ '/etc/pki/tls/certs/zabbix-agent.crt' if ansible_os_family == 'RedHat' else '/etc/ssl/certs/zabbix-agent.crt' }}
        zbxagent_tls_key_file: >-
          {{ '/etc/pki/tls/private/zabbix-agent.key' if ansible_os_family == 'RedHat' else '/etc/ssl/private/zabbix-agent.key' }}
        _zbxagent_cert_file: /tmp/zabbix-agent.crt
verifier:
  name: ansible
