---
- name: Prepare
  hosts:
    - subjects
  pre_tasks:
    - name: Create zabbix group
      become: true
      ansible.builtin.group:
        name: zabbix
        state: present
        system: true
    
    - name: Create zabbix user
      become: true
      ansible.builtin.user:
        name: zabbix
        group: zabbix
        system: true
        shell: /usr/sbin/nologin
        password: '!'
        password_lock: true
        home: /var/lib/zabbix
        createhome: false
        comment: Zabbix Monitoring System
        state: present
  roles:
    - role: trippsc2.hashi_vault.testing_ca
    - role: trippsc2.hashi_vault.signed_certificate
      vars:
        cert_certificate_path: "{{ zbxagent_tls_cert_file }}"
        cert_private_key_path: "{{ zbxagent_tls_key_file }}"
        cert_certificate_owner: zabbix
        cert_certificate_group: zabbix
        cert_private_key_owner: zabbix
        cert_private_key_group: zabbix
        cert_common_name: "{{ ansible_host }}"
        cert_subject_alternative_names:
          - "DNS:{{ inventory_hostname }}"
          - DNS:localhost
          - "IP:{{ ansible_host }}"
          - IP:127.0.0.1
        cert_extended_key_usage:
          - serverAuth
          - clientAuth
        cert_copy_ca_chain: true
        cert_ca_chain_path: "{{ zbxagent_tls_ca_file }}"
