---
zbxserver_configure_vault: true

zbxserver_database_type: postgresql

zbxserver_timezone: America/New_York

zbxserver_database_port: 5432
zbxserver_database_name: zabbix-server

zbxserver_vault_database_mount_point: zabbix
zbxserver_vault_database_path: database

zbxserver_user: zabbix

zbxserver_database_use_ssl: false
zbxserver_database_verify_host: true

zbxserver_server_port: 10051
zbxserver_display_name: ZABBIX

zbxserver_nginx_redirect_server_name:
  - _
zbxserver_nginx_server_name:
  - _

zbxserver_nginx_redirect_return_server_name: $host
zbxserver_nginx_max_body_size: 2M
