---
zbxserver_major_version: "{{ _zbxserver_default_major_version | default('7.0') }}"

zbxserver_configure_selinux: "{{ _zbxserver_default_configure_selinux | default(false) }}"
zbxserver_configure_firewalld: "{{ _zbxserver_default_configure_firewalld | default(false) }}"
zbxserver_configure_ufw: "{{ _zbxserver_default_configure_ufw | default(false) }}"
zbxserver_configure_logrotate: true
zbxserver_configure_vault: true
zbxserver_configure_mssql_odbc: true

zbxserver_user: zabbix
zbxserver_group: zabbix

zbxserver_database_name: zabbix-server

zbxserver_database_type: postgresql

zbxserver_allow_root: false

zbxserver_listen_port: 10051
zbxserver_listen_ip:
  - '0.0.0.0'

zbxserver_stats_allowed_ip:
  - '127.0.0.1'

zbxserver_service_manager_sync_frequency: 60

zbxserver_log_type: file
zbxserver_log_file: /var/log/zabbix/zabbix_server.log
zbxserver_log_file_size: >-
  {{ 0 if zbxserver_configure_logrotate else 1 }}

zbxserver_pid_file: /run/zabbix/zabbix_server.pid
zbxserver_socket_dir: /run/zabbix

zbxserver_database_host: localhost
zbxserver_database_port: 5432
zbxserver_db_tls_connect: unencrypted

zbxserver_allow_unsupported_db_versions: false

zbxserver_vault_database_mount_point: zabbix
zbxserver_vault_database_path: database

zbxserver_history_storage: false
zbxserver_history_storage_types:
  - uint
  - dbl
  - str
  - log
  - text

zbxserver_history_storage_date_index: false

zbxserver_export: false
zbxserver_export_file_size: 1G
zbxserver_export_type:
  - events
  - history
  - trends

zbxserver_start_pollers: 5
zbxserver_start_ipmi_pollers: 0
zbxserver_start_pollers_unreachable: 1
zbxserver_start_preprocessors: 3
zbxserver_start_history_pollers: 5
zbxserver_start_trappers: 5
zbxserver_start_pingers: 1
zbxserver_start_discoverers: 1
zbxserver_start_http_pollers: 1
zbxserver_start_timers: 1
zbxserver_start_escalators: 1
zbxserver_start_alerters: 3
zbxserver_start_java_pollers: 0
zbxserver_start_vmware_collectors: 0
zbxserver_start_snmp_trapper: 0
zbxserver_start_db_syncers: 4
zbxserver_start_proxy_pollers: 1
zbxserver_start_lld_processors: 2
zbxserver_start_report_writers: 0
zbxserver_start_odbc_pollers: 1

zbxserver_cache_size: 32M
zbxserver_history_cache_size: 16M
zbxserver_history_index_cache_size: 4M
zbxserver_trend_cache_size: 4M
zbxserver_trend_function_cache_size: 4M
zbxserver_value_cache_size: 8M
zbxserver_vmware_cache_size: 8M

zbxserver_use_java_gateway: false
zbxserver_java_gateway_port: 10052

zbxserver_vmware_frequency: 60
zbxserver_vmware_perf_frequency: 60
zbxserver_vmware_timeout: 10

zbxserver_snmp_trapper_file: /tmp/zabbix_traps.tmp

zbxserver_housekeeping_frequency: 1
zbxserver_max_housekeeper_delete: 5000
zbxserver_problem_housekeeping_frequency: 60

zbxserver_cache_update_frequency: 60

zbxserver_timeout: 3
zbxserver_trapper_timeout: 300

zbxserver_unreachable_period: 45
zbxserver_unavailable_delay: 60
zbxserver_unreachable_delay: 15

zbxserver_alert_scripts_path: /usr/lib/zabbix/alertscripts
zbxserver_external_scripts: /usr/lib/zabbix/externalscripts
zbxserver_fping_location: /usr/sbin/fping
zbxserver_fping6_location: /usr/sbin/fping6

zbxserver_tmp_dir: /tmp

zbxserver_proxy_config_frequency: 300
zbxserver_proxy_data_frequency: 1

zbxserver_vault_users_mount_point: zabbix
zbxserver_vault_users_base_path: users

zbxserver_vault_managed_users:
  - ansible

zbxserver_unmanaged_users: []
zbxserver_global_macros: []

zbxserver_logrotate_period: daily
zbxserver_logrotate_retention: 14
zbxserver_logrotate_mode: '0640'

zbxserver_templates: []
