---
- name: Ensure Zabbix Proxy group exists
  become: true
  ansible.builtin.group:
    name: "{{ zbxproxy_group }}"
    state: present
    system: true

- name: Ensure Zabbix Proxy user exists
  become: true
  ansible.builtin.user:
    name: "{{ zbxproxy_user }}"
    group: "{{ zbxproxy_group }}"
    password: '!'
    password_lock: true
    shell: /usr/sbin/nologin
    state: present
