---
_zbxserver_repo_package_url_by_major_version:
  '6.4': 'https://repo.zabbix.com/zabbix/6.4/debian/pool/main/z/zabbix-release/zabbix-release_6.4-1+debian11_all.deb'

_zbxserver_repo_package_url: "{{ _zbxserver_repo_package_url_by_major_version[zbxserver_major_version] }}"
