---
galaxy_info:
  author: Jim Tarpley (@trippsc2)
  namespace: trippsc2
  role_name: proxy_postgresql
  description: |
    This role installs PostgreSQL server for use by a Zabbix Proxy on a Linux system.

    This role uses **trippsc2.postgresql.install** to install PostgreSQL.
    The *pgsql_additional_hba_entries* variable is overridden by this role. The rest of the role variables can be set in the playbook or inventory.
  license: MIT

  min_ansible_version: '2.16'

  platforms:
    - name: Debian
      versions:
        - bookworm
    - name: EL
      versions:
        - '9'
        - '8'
    - name: Ubuntu
      versions:
        - noble
        - jammy
        - focal

  galaxy_tags: []

collections:
  - ansible.posix
  - community.hashi_vault
  - community.postgresql
  - trippsc2.hashi_vault
  - trippsc2.postgresql

dependencies:
  - role: trippsc2.zabbix.repo
