---
_zbxserver_default_pgsql_listen_on_local_only: "{{ not zbxserver_pgsql_standalone }}"
_zbxserver_default_pgsql_listen_on_all_addresses: "{{ zbxserver_pgsql_standalone }}"
_zbxserver_default_pgsql_install_timescaledb: "{{ zbxserver_use_timescaledb }}"

_zbxserver_default_timescaledb_schema_done_file_path: >-
  {{ _zbxserver_pgsql_base_directory }}/zbx_timescaledb_schema.done

_zbxserver_pgsql_listen_on_local_only: >-
  {{ pgsql_listen_on_local_only | default(_zbxserver_default_pgsql_listen_on_local_only) }}
_zbxserver_pgsql_listen_on_all_addresses: >-
  {{ pgsql_listen_on_all_addresses | default(_zbxserver_default_pgsql_listen_on_all_addresses) }}
_zbxserver_pgsql_install_timescaledb: >-
  {{ pgsql_install_timescaledb | default(_zbxserver_default_pgsql_install_timescaledb) }}
_zbxserver_pgsql_hba_entries: >-
  [
  {% if zbxserver_pgsql_standalone | bool %}
  {% for address in zbxserver_ip_addresses %}
    {
      "type": "host",
      "database": "{{ zbxserver_database_name }}",
      "user": "{{ zbxserver_user }}",
      "address": "{{ address }}/32",
      "auth_method": "{{ pgsql_password_encryption | default('scram-sha-256') }}"
    }{{ ',' if not loop.last }}
  {% endfor %}
  {% endif %}
  ]

_zbxserver_pgsql_schema_script_path_by_zabbix_major_version:
  '7.2': /usr/share/zabbix/sql-scripts/postgresql/server.sql.gz
  '7.0': /usr/share/zabbix-sql-scripts/postgresql/server.sql.gz

_zbxserver_timescaledb_schema_script_path_by_zabbix_major_version:
  '7.2': /usr/share/zabbix/sql-scripts/postgresql/timescaledb/schema.sql
  '7.0': /usr/share/zabbix-sql-scripts/postgresql/timescaledb/schema.sql

_zbxserver_pgsql_schema_script_path: >-
  {{ _zbxserver_pgsql_schema_script_path_by_zabbix_major_version[zbxserver_major_version] }}

_zbxserver_timescaledb_schema_script_path: >-
  {{ _zbxserver_timescaledb_schema_script_path_by_zabbix_major_version[zbxserver_major_version] }}

_zbxserver_timescaledb_schema_done_file_path: >-
  {{ zbxserver_timescaledb_schema_done_file_path | default(_zbxserver_default_timescaledb_schema_done_file_path) }}

zbx_major_version: "{{ zbxserver_major_version }}"
