---
- name: Ensure SQLite3 is installed
  become: true
  ansible.builtin.apt:
    name:
      - sqlite3
    state: present
    update_cache: true

- name: Ensure Zabbix SQL scripts package is installed
  become: true
  ansible.builtin.apt:
    name:
      - zabbix-sql-scripts
    state: present
    update_cache: true
