---
_zbxproxy_default_configure_selinux: false

_zbxproxy_default_additional_groups:
  - ssl-cert

_zbxproxy_selinux_packages:
  - python3-selinux
  - python3-semanage

_zbxproxy_env_file_path: /etc/default/zabbix-server
_zbxproxy_exec_stop_command: >-
  /bin/sh -c '[ -n "$1" ] && kill -s TERM "$1"' -- "$MAINPID"
