---
_zbxserver_default_major_version: >-
  {{ _zbxserver_supported_major_versions[0] }}

_zbxserver_package_name_by_database_type:
  postgresql: zabbix-server-pgsql
  mysql: zabbix-server-mysql

_zbxserver_package_name: >-
  {{ _zbxserver_package_name_by_database_type[zbxserver_database_type] }}

zbx_major_version: "{{ zbxserver_major_version }}"
