---
- name: Configure Zabbix user
  ansible.builtin.include_tasks: user.yml

- name: Install packages
  ansible.builtin.include_tasks: "install/{{ ansible_os_family }}.yml"

- name: Configure Zabbix Agent 2
  ansible.builtin.include_tasks: configure.yml

- name: Configure firewalld
  when:
    - zbxagent_configure_firewalld
  ansible.builtin.include_tasks: firewalld.yml

- name: Configure ufw
  when:
    - zbxagent_configure_ufw
  ansible.builtin.include_tasks: ufw.yml
