---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: libvirt
  cachier: machine
  parallel: true
platforms:
  - name: linux
    box: jtarpley/${MOLECULE_BOX:-rocky8_cis}
    memory: 2048
    cpus: 2
    groups:
      - subjects
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        vault_token: 47542cbc-6bf8-4fba-8eda-02e0a0d29a0a
        vault_url: "http://{{ hostvars['linux'].ansible_host }}:8200"        
      subjects:
        pgsql_ssl: true
        pgsql_ssl_ca_file: >-
          {{ '/etc/pki/ca-trust/source/anchors/ca_chain.crt' if ansible_os_family == 'RedHat' else '/usr/local/share/ca-certificates/ca_chain.crt' }}
        pgsql_ssl_cert_file: >-
          {{ '/etc/pki/tls/certs/server.crt' if ansible_os_family == 'RedHat' else '/etc/ssl/certs/server.crt' }}
        pgsql_ssl_key_file: >-
          {{ '/etc/pki/tls/private/server.key' if ansible_os_family == 'RedHat' else '/etc/ssl/private/server.key' }}
        pgsql_log_to_csvlog: true
        pgsql_log_to_syslog: true
        pgsql_vault_ssl_mode: verify-full
        pgsql_vault_access_hostname: "{{ ansible_fqdn }}"
        zbxserver_ip_addresses:
          - "{{ ansible_host }}"
        zbxserver_pgsql_standalone: ${MOLECULE_PGSQL_STANDALONE:-false}
        zbxserver_major_version: '${MOLECULE_ZABBIX_MAJOR_VERSION:-7.0}'
verifier:
  name: ansible
