---
- name: Remove default host
  delegate_to: localhost
  community.zabbix.zabbix_host:
    host_name: Zabbix server
    state: absent

- name: Create Zabbix global macros
  delegate_to: localhost
  loop: "{{ zbxserver_global_macros }}"
  community.zabbix.zabbix_globalmacro:
    macro_type: "{{ item.type | default('text') }}"
    macro_name: "{{ item.name }}"
    macro_value: "{{ item.value }}"
    state: present
