---
- name: Validate
  ansible.builtin.import_tasks: validate.yml

- name: Ensure Zabbix user exists
  ansible.builtin.import_tasks: user.yml

- name: Ensure Zabbix Server is installed
  ansible.builtin.include_tasks: "install/{{ ansible_os_family }}.yml"

- name: Ensure SELinux is configured for use with Zabbix
  when:
    - zbxserver_configure_selinux
  ansible.builtin.include_tasks: selinux.yml

- name: Configure firewalld
  when:
    - zbxserver_configure_firewalld
  ansible.builtin.include_tasks: firewalld.yml

- name: Configure ufw
  when:
    - zbxserver_configure_ufw
  ansible.builtin.include_tasks: ufw.yml

- name: Configure MSSQL ODBC
  when:
    - zbxserver_configure_mssql_odbc
  ansible.builtin.include_tasks: odbc/main.yml

- name: Ensure Zabbix is configured and started
  ansible.builtin.import_tasks: configure.yml

- name: Configure Zabbix local users
  ansible.builtin.import_tasks: zabbix-users.yml

- name: Perform first app configuration steps
  ansible.builtin.import_tasks: first-steps.yml

- name: Import Zabbix templates
  ansible.builtin.include_tasks: templates.yml
