---
- name: Ensure SELinux management packages are installed
  become: true
  ansible.builtin.package:
    name: "{{ _zbxserver_selinux_packages }}"
    state: present

- name: Ensure Zabbix is allowed to connect to various TCP ports
  become: true
  ansible.posix.seboolean:
    name: zabbix_can_network
    state: true
    persistent: true
