---
- name: Ensure Zabbix Server group exists
  become: true
  ansible.builtin.group:
    name: "{{ zbxserver_group }}"
    state: present
    system: true

- name: Ensure Zabbix Server user exists
  become: true
  ansible.builtin.user:
    name: "{{ zbxserver_user }}"
    group: "{{ zbxserver_group }}"
    groups: "{{ zbxserver_additional_groups | default(omit) }}"
    system: true
    password: '!'
    password_lock: true
    shell: /usr/sbin/nologin
    home: /var/lib/zabbix
    createhome: false
    comment: Zabbix Monitoring System
    state: present
