---
- name: Validate EL major version
  when:
    - ansible_os_family == 'RedHat'
  ansible.builtin.assert:
    that:
      - zbxserver_major_version in _zbxserver_el_supported_major_versions[ansible_distribution_major_version]
    fail_msg: "{{ ansible_distribution }} {{ ansible_distribution_major_version }} is not supported running Zabbix {{ zbxserver_major_version }}. Supported versions for this distribution are: {{ _zbxserver_el_supported_major_versions[ansible_distribution_major_version] | join(', ') }}."
    success_msg: "{{ ansible_distribution }} {{ ansible_distribution_major_version }} is supported running Zabbix {{ zbxserver_major_version }}."

- name: Validate non-EL major version
  when:
    - ansible_os_family != 'RedHat'
  ansible.builtin.assert:
    that:
      - zbxserver_major_version in _zbxserver_non_el_supported_major_versions[ansible_distribution_release]
    fail_msg: "{{ ansible_distribution }} is not supported running Zabbix {{ zbxserver_major_version }}. Supported versions for this distribution are: {{ _zbxserver_non_el_supported_major_versions[ansible_distribution_release] | join(', ') }}."
    success_msg: "{{ ansible_distribution }} is supported running Zabbix {{ zbxserver_major_version }}."
