---
galaxy_info:
  author: Jim Tarpley (@trippsc2)
  namespace: trippsc2
  role_name: server
  description: This role installs and configures the Zabbix server on a Linux system.
  license: MIT

  min_ansible_version: '2.16'

  platforms:
    - name: Debian
      versions:
        - bookworm
    - name: EL
      versions:
        - '9'
        - '8'
    - name: Ubuntu
      versions:
        - noble
        - jammy

collections:
  - ansible.posix
  - community.general
  - community.hashi_vault
  - community.zabbix
  - trippsc2.hashi_vault

dependencies:
  - role: trippsc2.zabbix.repo
