---
_zbx_repo_package_url_by_major_version:
  '7.0': https://repo.zabbix.com/zabbix/7.0/rhel/9/x86_64/zabbix-release-7.0-3.el9.noarch.rpm
  '6.4': https://repo.zabbix.com/zabbix/6.4/rhel/9/x86_64/zabbix-release-6.4-2.el9.noarch.rpm

_zbx_repo_package_url: "{{ _zbx_repo_package_url_by_major_version[zbx_major_version] }}"
