---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: libvirt
  cachier: machine
  parallel: true
platforms:
  - name: vault
    box: jtarpley/rocky9_cis
    memory: 2048
    cpus: 2
    provider_options:
      default_prefix: zabbix_agent2_win_
    groups:
      - vault_server
  - name: win
    box: jtarpley/${MOLECULE_BOX:-w2022_cis}
    memory: 2048
    cpus: 2
    provider_options:
      default_prefix: zabbix_agent2_win_
    groups:
      - subjects
      - windows
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        vault_token: 47542cbc-6bf8-4fba-8eda-02e0a0d29a0a
        vault_url: "http://{{ hostvars['vault'].ansible_host }}:8200"
      subjects:
        zbxagent_install_ember_plus_plugin: true
        zbxagent_install_mongodb_plugin: true
        zbxagent_install_mssql_plugin: true
        zbxagent_install_pgsql_plugin: true
        zbxagent_servers:
          - "{{ hostvars['vault'].ansible_host }}"
        zbxagent_active_servers:
          - "{{ hostvars['vault'].ansible_host }}"
        zbxagent_tls_connect: cert
        zbxagent_tls_accept: cert
        zbxagent_tls_ca_file: C:\Windows\Temp\vault.crt
        zbxagent_tls_cert_file: C:\Windows\Temp\zabbix-agent.crt
        zbxagent_tls_key_file: C:\Windows\Temp\zabbix-agent.key
      vault_server:
        _zbxagent_ca_file: >-
          {{ '/etc/pki/ca-trust/source/anchors/vault.crt' if ansible_os_family == 'RedHat' else '/usr/local/share/ca-certificates/vault.crt' }}
      windows:
        ansible_shell_type: powershell
        ansible_become_method: runas
        ansible_become_user: SYSTEM
        ansible_password: vagrant
        ansible_ssh_common_args: '-o PreferredAuthentications=password -o PubkeyAuthentication=no -o UserKnownHostsFile=/dev/null -o ControlMaster=auto -o ControlPersist=60s -o ForwardX11=no -o LogLevel=ERROR -o StrictHostKeyChecking=no'
verifier:
  name: ansible
