---
- name: Prepare Vault
  hosts:
    - vault_server
  roles:
    - role: trippsc2.hashi_vault.testing_ca

- name: Prepare Zabbix agent certificate
  hosts:
    - subjects
  roles:
    - role: trippsc2.hashi_vault.signed_certificate
      vars:
        cert_certificate_path: "{{ zbxagent_tls_cert_file }}"
        cert_private_key_path: "{{ zbxagent_tls_key_file }}"
        cert_common_name: "{{ ansible_host }}"
        cert_subject_alternative_names:
          - "DNS:{{ inventory_hostname }}"
          - DNS:localhost
          - "IP:{{ ansible_host }}"
          - IP:127.0.0.1
        cert_extended_key_usage:
          - serverAuth
          - clientAuth
        cert_copy_ca_chain: true
        cert_ca_chain_path: "{{ zbxagent_tls_ca_file }}"
