---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: libvirt
  cachier: machine
  parallel: true
platforms:
  - name: linux
    box: jtarpley/${MOLECULE_BOX:-rocky8_cis}
    memory: 2048
    cpus: 2
    provider_options:
      default_prefix: zabbix_nginx_standalone_
    groups:
      - subjects
  - name: database
    box: jtarpley/${MOLECULE_BOX:-rocky8_cis}
    memory: 2048
    cpus: 2
    provider_options:
      default_prefix: zabbix_nginx_standalone_
    groups:
      - zabbix_database
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        vault_token: 47542cbc-6bf8-4fba-8eda-02e0a0d29a0a
        vault_url: "http://{{ hostvars['linux'].ansible_host }}:8200"
        zbxserver_major_version: '${MOLECULE_ZABBIX_MAJOR_VERSION:-7.0}'
        zbxserver_configure_vault: true
        zbxserver_database_type: ${MOLECULE_ZABBIX_DATABASE_TYPE:-postgresql}
        _zbxserver_ca_file: >-
          {{ '/etc/pki/ca-trust/source/anchors/vault.crt' if ansible_os_family == 'RedHat' else '/usr/local/share/ca-certificates/vault.crt' }}
      subjects:
        zbxserver_database_host: "{{ hostvars['database'].ansible_host }}"
        zbxserver_database_port: 5432
        zbxserver_database_use_ssl: true
        zbxserver_database_ca_file: "{{ _zbxserver_ca_file }}"
        zbxserver_database_verify_host: false
        zbxserver_vault_url: "{{ vault_url }}"
        zbxserver_vault_token: "{{ vault_token }}"
        zbxserver_server_host: localhost
        zbxserver_web_server_certificate_path: >-
          {{ '/etc/pki/tls/certs/zabbix-web.crt' if ansible_os_family == 'RedHat' else '/etc/ssl/certs/zabbix-web.crt' }}
        zbxserver_web_server_private_key_path: >-
          {{ '/etc/pki/tls/private/zabbix-web.key' if ansible_os_family == 'RedHat' else '/etc/ssl/private/zabbix-web.key' }}
      zabbix_database:
        pgsql_major_version: ${MOLECULE_PGSQL_MAJOR_VERSION:-16}
        pgsql_ssl: true
        pgsql_ssl_ca_file: "{{ _zbxserver_ca_file }}"
        pgsql_ssl_cert_file: >-
          {{ '/etc/pki/tls/certs/pgsql.crt' if ansible_os_family == 'RedHat' else '/etc/ssl/certs/pgsql.crt' }}
        pgsql_ssl_key_file: >-
          {{ '/etc/pki/tls/private/pgsql.key' if ansible_os_family == 'RedHat' else '/etc/ssl/private/pgsql.key' }}
        pgsql_log_to_csvlog: true
        pgsql_log_to_syslog: true
        pgsql_vault_ssl_mode: verify-full
        pgsql_vault_access_hostname: "{{ ansible_host }}"
        pgsql_vault_ip_addresses:
          - "{{ hostvars['linux'].ansible_host }}"
        zbxserver_pgsql_standalone: true
        zbxserver_ip_addresses:
          - "{{ hostvars['linux'].ansible_host }}"
verifier:
  name: ansible
