---
- name: Validate
  ansible.builtin.import_tasks: validate.yml

- name: Set PostgreSQL facts
  ansible.builtin.set_fact:
    pgsql_listen_on_local_only: >-
      {{ _zbxserver_pgsql_listen_on_local_only }}
    pgsql_listen_on_all_addresses: >-
      {{ _zbxserver_pgsql_listen_on_all_addresses }}
    pgsql_install_timescaledb: >-
      {{ _zbxserver_pgsql_install_timescaledb }}
    pgsql_additional_hba_entries: >-
      {{ _zbxserver_pgsql_hba_entries + zbxserver_pgsql_additional_hba_entries }}

- name: Include PostgreSQL role
  ansible.builtin.include_role:
    name: trippsc2.postgresql.install

- name: Configure Vault
  when:
    - zbxserver_configure_vault
  ansible.builtin.include_tasks: vault.yml

- name: Create user
  ansible.builtin.include_tasks: user.yml

- name: Install Zabbix packages
  ansible.builtin.include_tasks: "install/{{ ansible_os_family }}.yml"

- name: Configure database
  ansible.builtin.import_tasks: configure.yml
