---
- name: Include OS specific variables
  ansible.builtin.include_vars: "{{ _file }}"
  vars:
    _file: "{{ lookup('first_found', _params) }}"
    _params:
      files:
        - "{{ ansible_distribution }}-{{ ansible_distribution_release | default('') }}.yml"
        - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_os_family }}.yml"
        - fallback.yml
      paths:
        - "{{ role_path }}/vars"

- name: Validate OS is supported
  ansible.builtin.assert:
    that:
      - _zbxserver_os_is_supported
    fail_msg: "This role does not support {{ ansible_distribution }} {{ ansible_distribution_version }}."
    success_msg: "This role supports {{ ansible_distribution }} {{ ansible_distribution_version }}."

- name: Validate Zabbix major version
  ansible.builtin.assert:
    that:
      - zbxserver_major_version in _zbxserver_supported_major_versions
    fail_msg: "This role does not support Zabbix Server {{ zbxserver_major_version }} on {{ ansible_distribution }} {{ ansible_distribution_version }}."
    success_msg: "This role supports Zabbix Server {{ zbxserver_major_version }} on {{ ansible_distribution }} {{ ansible_distribution_version }}."

- name: Validate PostgreSQL listen addresses
  when:
    - zbxserver_pgsql_standalone
    - pgsql_listen_on_local_only is defined
  ansible.builtin.assert:
    that:
      - not pgsql_listen_on_local_only | bool
    fail_msg: PostgreSQL listen addresses must not be restricted to local only when PostgreSQL is standalone.
    success_msg: PostgreSQL listen addresses are not restricted to local only.

- name: Validate Zabbix server IP addresses are defined
  when:
    - zbxserver_pgsql_standalone
  ansible.builtin.assert:
    that:
      - zbxserver_ip_addresses is defined
    fail_msg: Zabbix server IP addresses must be defined when PostgreSQL is standalone.
    success_msg: Zabbix server IP addresses are defined.
